env:
  node: true
  es2022: true
  jest: true
extends:
  - standard
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:prettier/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-unused-vars: error
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
  prettier/prettier: error
  no-new: 0
  no-useless-constructor: off